# Generated by Django 3.0.4 on 2020-06-02 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(blank=True, default='', max_length=200)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=2)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=200)),
                ('releasedYear', models.CharField(blank=True, default='', max_length=200)),
                ('topic', models.CharField(blank=True, default='', max_length=200)),
                ('timeLength', models.CharField(blank=True, default='', max_length=200)),
                ('budget', models.CharField(blank=True, default='', max_length=200)),
                ('reviews', models.CharField(blank=True, default='', max_length=200)),
                ('score', models.CharField(blank=True, default='', max_length=200)),
                ('awards', models.CharField(blank=True, default='', max_length=200)),
                ('actors', models.ManyToManyField(to='movies.Actor')),
                ('genre', models.ManyToManyField(to='movies.Genre')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
