# Generated by Django 3.0.4 on 2020-03-22 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=200)),
                ('movieCategory', models.CharField(blank=True, default='', max_length=200)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
