# Generated by Django 3.0.4 on 2020-06-05 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_auto_20200605_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='budget',
            field=models.IntegerField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='movie',
            name='releasedYear',
            field=models.IntegerField(blank=True, default='', max_length=200),
        ),
        migrations.RemoveField(
            model_name='movie',
            name='reviews',
        ),
        migrations.AddField(
            model_name='movie',
            name='reviews',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='movies.Review'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='movie',
            name='score',
        ),
        migrations.AddField(
            model_name='movie',
            name='score',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='movies.Score'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='score',
            name='movieScore',
            field=models.IntegerField(max_length=200),
        ),
    ]
