# Generated by Django 3.0.4 on 2020-06-05 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_auto_20200605_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='surname',
            field=models.TextField(blank=True, default='', max_length=200),
        ),
    ]
